# Generated by Django 5.0.1 on 2024-01-19 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_salle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='matiere',
            field=models.CharField(default='matiere', max_length=100),
        ),
        migrations.AddField(
            model_name='salle',
            name='capacite',
            field=models.IntegerField(default=0, max_length=100),
        ),
    ]
