# Generated by Django 5.0.1 on 2024-01-20 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_salle', '0003_alter_reservation_matiere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='matiere',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
