# Generated by Django 5.0.1 on 2024-01-20 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_salle', '0004_alter_reservation_matiere'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='terminee',
            field=models.BooleanField(default=False),
        ),
    ]
