# Generated by Django 5.0.1 on 2024-01-20 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_salle', '0005_reservation_terminee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='terminee',
        ),
    ]
