# Generated by Django 5.0.1 on 2024-01-21 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_salle', '0006_remove_reservation_terminee'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='terminee',
            field=models.BooleanField(default=False),
        ),
    ]
